apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pacman-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/gitops-cookbook/pacman-kikd.git"
    - name: GIT_REF
      type: string
      default: "main"
    - name: DESTINATION_IMAGE
      type: string
      default: "quay.io/gitops-cookbook/pacman-kikd:latest"
    - name: CONTEXT_DIR
      type: string
      default: "."
    - name: CONFIG_GIT_REPO
      type: string
      default: 'https://github.com/gitops-cookbook/pacman-kikd-manifests.git'
    - name: CONFIG_GIT_REF
      type: string
      default: main
  workspaces:
    - name: app-source
    - name: maven-settings
    - name: config-source
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
        - name: deleteExisting
          value: true
        - name: verbose
          value: true
    - name: build-app
      taskRef:
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: app-source
      runAfter: 
        - fetch-repo
      params:
        - name: GOALS
          value: 
            - -DskipTests
            - clean
            - package
        - name: CONTEXT_DIR
          value: "$(params.CONTEXT_DIR)"
    - name: build-push-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: app-source
      runAfter:
        - build-app
      params:
        - name: IMAGE
          value: "$(params.DESTINATION_IMAGE)"
        - name: DOCKERFILE
          value: "$(params.CONTEXT_DIR)/Dockerfile"
        - name: CONTEXT
          value: "$(params.CONTEXT_DIR)"
    - name: git-update-deployment
      taskRef:
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: config-source
      runAfter:
        - build-push-image
      params:
        - name: GIT_REPOSITORY
          value: $(params.CONFIG_GIT_REPO)
        - name: NEW_IMAGE
          value: $(params.DESTINATION_IMAGE)
        - name: NEW_DIGEST
          value: $(tasks.build-push-image.results.IMAGE_DIGEST)
        - name: KUSTOMIZATION_PATH
          value: "env/dev"
        - name: GIT_REF
          value: $(params.CONFIG_GIT_REF)
