apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tekton-greeter-pipeline-hub
spec:
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/gitops-cookbook/tekton-tutorial-greeter.git"
    - name: GIT_REF
      type: string
      default: "master"
    - name : DESTINATION_IMAGE
      type: string
      default: "quay.io/gitops-cookbook/tekton-greeter:lastest"
    - name: CONTEXT_DIR
      type: string
      default: "quarkus"
  workspaces:
    - name: app-source
    - name: maven-settings
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
        - name: deleteExisting
          value: true
        - name: verbose
          value: true
    - name: build-app
      taskRef:
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: app-source
      runAfter: 
        - fetch-repo
      params:
        - name: GOALS
          value: 
            - -DskipTests
            - clean
            - package
        - name: CONTEXT_DIR
          value: "$(params.CONTEXT_DIR)"
    - name: build-push-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: app-source
      runAfter:
        - build-app
      params:
        - name: IMAGE
          value: "$(params.DESTINATION_IMAGE)"
        - name: DOCKERFILE
          value: "$(params.CONTEXT_DIR)/Dockerfile"
        - name: CONTEXT
          value: "$(params.CONTEXT_DIR)"
    - name: deploy
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-image
      params:
        - name: script
          value: "kubectl create deploy tekton-greeter --image=$(params.DESTINATION_IMAGE) --dry-run=true -o yaml | kubectl apply -f -"

