apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tekton-greeter-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REF
      type: string
    - name : DESTINATION_IMAGE
      type: string
  workspaces:
    - name: pipeline-shared
  tasks:
    - name: build-push-app
      taskRef:
        name: build-push-app
      params:
        - name: url
          value: "$(params.GIT_REPO)"
        - name: revision
          value: "$(params.GIT_REF)"
        - name: destinationImage
          value: "$(params.DESTINATION_IMAGE)"
      workspaces:
        - name: source
          workspace: pipeline-shared
    - name: deploy-app
      taskRef:
        name: kubectl
      params:
        - name: SCRIPT
          value: "kubectl create deploy tekton-greeter --image=$(params.DESTINATION_IMAGE) --dry-run=client -o yaml | kubectl apply -f -"
      runAfter:
        - build-push-app

